services:
  app-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-server
    depends_on:
      - router
      - dns-server
      - target
      - ollama
      - agent-db
      - app-db
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - AGENT_DB_URI=${AGENT_DB_URI}
      - APP_DB_URI=${APP_DB_URI}
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "8000:8000"
    volumes:
      - app-file-data:/app/storage/documents
    dns:
      - 192.168.20.10
    networks:
      agent-network:
      lab-a:
        ipv4_address: 192.168.10.10
      management:
        ipv4_address: 172.30.0.10

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - agent-network

  router:
    build:
      context: ./devices/router
    container_name: router
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      net.ipv4.ip_forward: "1"
    networks:
      lab-a:
        ipv4_address: 192.168.10.2
      lab-b:
        ipv4_address: 192.168.20.2
      management:
        ipv4_address: 172.30.0.20

  dns-server:
    build:
      context: ./devices/dns
    container_name: dns-server
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      lab-b:
        ipv4_address: 192.168.20.10
      management:
        ipv4_address: 172.30.0.30

  target:
    build:
      context: ./devices/target
    container_name: target
    cap_add:
      - NET_ADMIN
      - NET_RAW
    dns:
      - 192.168.20.10
    networks:
      lab-b:
        ipv4_address: 192.168.20.20
      management:
        ipv4_address: 172.30.0.40

  agent-db:
    image: postgres:17
    container_name: agent-db
    environment:
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: password
      POSTGRES_DB: agent_db
    volumes:
      - agent-postgres-data:/var/lib/postgresql/data
    networks:
      - agent-network

  app-db:
    image: pgvector/pgvector:pg16
    container_name: app-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    volumes:
      - app-postgres-data:/var/lib/postgresql/data
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge

  lab-a:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24

  lab-b:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24

  management:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24

volumes:
  ollama-data:
  agent-postgres-data:
  app-postgres-data:
  app-file-data: